### ISSUE TITLE
XSS vulnerability everywhere

### ISSUE THREAD

**Issue by AlexDaniel** [ajgraves/aneuch#15]
Although taint checking is on, it seems like there are no checks at all.

Some examples (you have to make someone click this link):
* ``?do=admin;page=index<script>alert('badum-tss')</script>``
* ``?do=admin<script>alert('badum-tss')</script>test`` (even though it errors out, javascript still runs)
* *possibly more…*

This, however, does not let you to leave some malicious javascript on the page and then just sit back.

But this does:
![screenshot with <b> injected into page name](https://files.progarm.org/2015-09-01-043826_804x355_scrot.png)
(arbitrary html injected into page name. In this case, it is ``<b>``)

Please note that I was actually aiming for write access vulnerability (mentioning it because it can be seen on the screenshot). Possibly problematic lines:
```perl
sub WriteDB {
  # We receive file name, and hash
  my $filename = shift;
  my %filedata = %{shift()};
  $filename =~ m/^(.*)$/; $filename = $1;
  open(FILE, ">$filename") or push @Messages, "WriteDB: Unable to write to $filename: $!";
```
It seems like taint checking has turned on its alarms on this code, but was just silenced off. The problem with arbitrary filenames is that you can pass any kind of stuff there, for example ``/../../somefile``. This should work! Unfortunately (luckily), **I was unable to get it to work, but it should be investigated**. Basically the first character will be used as a path in $PageDir (let's say ``data/``), which turns it into ``data///../../somefile`` – perfectly valid file path. I wonder why I couldn't get it to write the file…

(Sorry if you don't like such reports to be posted on GitHub. I see no problem in posting it here publicly. The whole thing is about poking ``<b>`` into various places for 30 minutes)

**Comment by AlexDaniel** [comment]
Maybe I should elaborate on the path in page name thing.

Here, some stuff is stripped: https://github.com/ajgraves/aneuch/blob/master/aneuch.pl#L172
But it does not matter. It seems like this code is not even related to ``DoPostingDiscuss`` which does this:
```perl
AppendPage(GetParam('file'), GetParam('text'), GetParam('uname'),
	  GetParam('url'));
```
That's without any checks. There are no checks in ``GetParam`` too. ``AppendPage`` simply calls ``WriteDB``, so a weird path with dots and slashes will actually pass all the way through. If you find what was breaking my perfect attempt to write into arbitrary path, please tell me, that's interesting.

**Comment by ajgraves** [comment]
Thank you for the report! I will begin checking into this now.

**Comment by ajgraves** [comment]
For documentation's sake:

Places where sanitization is needed:
* DoPostingSpam
* DoPostingEditing
* DoPostingDiscuss
* DoPostingUpload
* DoPosting
* WritePage

**Comment by AlexDaniel** [comment]
What about sanitizing it right in ``sub GetParam``? Not that you should not do sanitization (other than HtmlQuote) in places you mentioned, but if you forget to sanitize something, at least it will be html-quoted. That's what Oddmuse does, for example.

**Comment by ajgraves** [comment]
That thought occurred to me, especially because (from what I can tell right now) everything that needs sanitization is going to be calling `GetParam` for 'file'.

I have modified `GetParam` to call `QuoteHTML` before returning a value.

**Comment by ajgraves** [comment]
To clarify, my comments about sanitizing are in regards to file names. There are quite a few calls where this isn't checked for validity.

**Comment by ajgraves** [comment]
@AlexDaniel to answer your question about what is breaking your attempt to write into an arbitrary path, the answer can be found in [`sub DoPosting`](https://github.com/ajgraves/aneuch/blob/master/aneuch.pl#L2671). Any slashes in the file name are [removed](https://github.com/ajgraves/aneuch/blob/master/aneuch.pl#L2676), and then all leading periods are [removed](https://github.com/ajgraves/aneuch/blob/master/aneuch.pl#L2678).

So it seems like the arbitrary file path is a non-issue, however I'll keep checking the code to make sure. Work continues on the XSS portion as well.

**Comment by AlexDaniel** [comment]
@ajgraves are you sure? Because, even if it is removed, ``sub DoPostingDiscuss`` does this:
```perl
	AppendPage(GetParam('file'), GetParam('text'), GetParam('uname'),
	  GetParam('url'));
```
That is, it GetParam-s the original untreated value. Given that I was unable to write into arbitrary path (although I did create some pages with dots and slashes), there is probably something that strips it, or at least affects it in some way. But yeah, I could also be wrong.

**Comment by AlexDaniel** [comment]
Oh, and also, when I was trying to write into arbitrary path, there was no page file created. So it just failed to write it, it did not write into sanitized file path.

**Comment by ajgraves** [comment]
You know what @AlexDaniel, I was thinking that after I typed my response. So in `sub DoPosting` I'm going to have to call `SetParam` on 'file' to replace it with the "sanitized" file name.

Thinking about it, the failure to write to an arbitrary path may be more related to system permissions then. I know on my server CGI scripts are executed under my user name, so it would be unable to write in any path where my user ID (or group) did not have write access.

**Comment by ajgraves** [comment]
I believe I have this corrected in commit a00953976f, however there's a few other areas I need to check. Since `GetParam` now calls `QuoteHTML` then there shouldn't be an issue going forward, however any existing "bad" data would be a problem.

**Comment by ajgraves** [comment]
I also "stole" three things from Oddmuse's Refactoring page:
1. Replace 'use vars' with 'our'
2. Two-var open
3. Bareword file handle

**Comment by AlexDaniel** [comment]
It's OK, that's why this page is public :)

However, I don't think that I will have a chance to review this commit in detail. It is a bit too hard for me when changes are not split into smaller commits. Some time later I will probably try to shove shitty data into various places (this is usually much easier than trying to find an error in the code). Not any time soon though.

**Comment by AlexDaniel** [comment]
If you feel that it is fixed then you can close this issue. If I ever have time to find more stuff I'll leave a comment or write an email. Thanks!
